feature/ss-414
lunasoft/sw-sdk-nodejs pull request #13
Opened 2023-11-27 21:41 UTC by SebastianSW

2023-11-28 00:27 UTC, FerCarrilloM approved these changes

2023-11-29 00:21 UTC, ReyesSW approved these changes

2023-11-29 17:55 UTC, SwAeyrton requested changes

2023-11-29 17:55 UTC, SwAeyrton commented on package.json
> -    "name": "Flavio Ochoa",
Considero que se debe dejar el autor principal de la libreria, se pueden agregar mas sin sustituirlo.

2023-11-29 18:07 UTC, SebastianSW commented on package.json
> -    "name": "Flavio Ochoa",
Se agregan los nombres de quienes han contribuido a la librería

2023-11-29 18:10 UTC, merged